### ISSUE TITLE
Changelog "Expand/Hide" doesn't work

### ISSUE THREAD

**Issue by fserafin** [XiaomiFirmwareUpdater/xmfirmwareupdater.github.io#16]
In the download page (eg. [here](https://xmfirmwareupdater.com/hyperos/ziyi/stable%20beta/OS1.0.9.0.ULLMIXM/))
the link **Changelog "Expand/Hide"** doesn't actually expand the collapsable div under the link.

This should be because of a bug present in jQuery v3.5.0 which affect the "Collapse" function of bootstrap (v.4.3.1).

The jQuery v3.5.1  should fix the issue (ref [here](https://github.com/twbs/bootstrap/issues/30553#issuecomment-623866824))

thanks, Francesco

**Comment by yshalsager** [comment]
Thanks! @fserafin
